// <auto-generated />
namespace IdintityProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class FK_CourseGradess : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FK_CourseGradess));
        
        string IMigrationMetadata.Id
        {
            get { return "202204191313066_FK_CourseGradess"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
